/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIdImport } from './routes/auth.$id'
import { Route as ApiAuthCallbackGoogleImport } from './routes/api.auth.callback.google'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIdRoute = AuthIdImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/$id' | '/api/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/$id' | '/api/auth/callback/google'
  id: '__root__' | '/' | '/auth/$id' | '/api/auth/callback/google'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthIdRoute: typeof AuthIdRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthIdRoute: AuthIdRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/$id",
        "/api/auth/callback/google"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/$id": {
      "filePath": "auth.$id.tsx"
    },
    "/api/auth/callback/google": {
      "filePath": "api.auth.callback.google.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
